### ISSUE TITLE
Changed map is not updated in the server info section "map" after using the "get server info" button.

### ISSUE THREAD

**Issue by olli-e** [olli-e/ISRT-Insurgency-Sandstorm-RCON-Query-Tool#3]
Good improvements, so far. The "change map" function works fine, the night/day switch is of value. However, the changed map is not updated in the server info section "map" after using the "get server info" button. Thumbs up!

**Comment by sargolin** [comment]
Wasn't able to recreate the issue - perhaps a timeout, port or other timing issue. Will investigate further if the user reports in.

**Comment by sargolin** [comment]
We assessed this and the problem is, that the server is not updating the query after a "random" map change by voting random or just leaving it like that. I opened a ticket with NWI, since this is a problem, I cannot solve.

**Comment by sargolin** [comment]
https://sandstorm-support.newworldinteractive.com/hc/en-us/requests/584
