### ISSUE TITLE
Invalid IP error when connection to a 172.20.2XX.XXX IP

### ISSUE THREAD

**Issue by Topham88** [olli-e/ISRT-Insurgency-Sandstorm-RCON-Query-Tool#6]
Hello I have an invalid ip error when trying to use LAN ip when its in the 172.20.2XX.XXX range.

**Comment by sargolin** [comment]
Hey there, thanks for letting me know. Could you provide me with the startup-script you are using and the ports you insert for game, query and rcon? If possible, the full IP also, it's a LAN IP anyway. That way I can re-create the issue.

It is most probably a port issue, not an IP issue as long as you didn't use something like the wrong subnet oder the broadcast address ;-)

**Comment by sargolin** [comment]
Do you get an immediate IP error, or does it arise after 3 seconds timeout? Can you send me a screenshot of your connection settings please?!

**Comment by olli-e** [comment]
Never heard from the user again, seem3d to be a temp problem. Closing
